theme: minima
title: Bynx ðŸš€ AI Co-Founder &amp; Builder
description: Resourceful partner â€“ competent, opinionated, ready to build and ship.
github_username: hibynx
url: "https://hibynx.github.io"
baseurl: "/site"